// Switches this machine to a named environment profile -- URL AND credentials together, in one command,
// instead of hand-editing .env's credential block every time you cross servers (confirmed live 2026-09-23/24:
// doing this by hand is what caused a mismatched credentials-vs-server-name comment to sit in .env unnoticed).
//
// A "profile" is a real config/environments/<name>.env file (gitignored, holds real credentials -- see
// config/environments/example.env for the template). This script copies it verbatim into .env and points
// tce_settings.json at its BASE_URL, exactly like scripts/set-server.js does for the URL alone.
//
// Usage:
//   node scripts/set-env.js qa
//   node scripts/set-env.js new-server
//   node scripts/set-env.js --reset        (alias for the DEFAULT_PROFILE below)

const fs = require('fs');
const os = require('os');
const path = require('path');
const { setTceServerUrl } = require('./lib/tce-settings');

const ENVIRONMENTS_DIR = path.join(__dirname, '..', 'config', 'environments');
const ENV_PATH = path.join(__dirname, '..', '.env');
// The environment "reset" returns to -- CLAUDE.md documents this as the project's primary target.
const DEFAULT_PROFILE = 'qa';

function fail(message) {
  console.error(`\nset-env: ${message}`);
  process.exit(1);
}

function main() {
  let name = process.argv[2];
  if (name === '--reset') name = DEFAULT_PROFILE;
  if (!name) {
    const available = listProfiles();
    fail(
      `missing profile name.\n\n  Usage: node scripts/set-env.js <name>\n  node scripts/set-env.js --reset\n\n` +
        `Available profiles: ${available.length ? available.join(', ') : '(none found in config/environments/)'}`
    );
  }

  const profilePath = path.join(ENVIRONMENTS_DIR, `${name}.env`);
  if (!fs.existsSync(profilePath)) {
    const available = listProfiles();
    fail(
      `no profile named "${name}" (looked for ${profilePath}).\n\n` +
        `Available profiles: ${available.length ? available.join(', ') : '(none found)'}\n` +
        `To add one: copy config/environments/example.env to config/environments/${name}.env and fill it in.`
    );
  }

  const profileContent = fs.readFileSync(profilePath, 'utf8');
  const url = extractBaseUrl(profileContent);
  if (!url) fail(`${profilePath} has no BASE_URL= line -- can't tell which server this profile targets.`);

  let result;
  try {
    result = setTceServerUrl(url);
  } catch (err) {
    fail(err.message);
  }
  if (result.droppedCount > 0) {
    console.log(`Dropping ${result.droppedCount} extra saved profile(s) -- this script keeps exactly one.`);
  }

  fs.writeFileSync(
    ENV_PATH,
    `# Generated by "npm run set-env ${name}" -- edit config/environments/${name}.env instead of this file` +
      ` directly, or your changes will be overwritten on the next switch.${os.EOL}${os.EOL}${profileContent}`
  );

  console.log(`
Switched to environment: ${name}  (${url})

  tce_settings.json -> updated
  .env               -> replaced with config/environments/${name}.env

Run "npm run set-env -- --reset" any time to return to the default (${DEFAULT_PROFILE}).
`);
}

function listProfiles() {
  if (!fs.existsSync(ENVIRONMENTS_DIR)) return [];
  return fs
    .readdirSync(ENVIRONMENTS_DIR)
    .filter((f) => f.endsWith('.env') && f !== 'example.env')
    .map((f) => f.replace(/\.env$/, ''));
}

function extractBaseUrl(content) {
  const match = content.match(/^\s*BASE_URL\s*=\s*(.+)\s*$/m);
  return match ? match[1].trim() : null;
}

main();
